version: '3.8'
services:
  crawler:
    build:
      extra_hosts:
        - "host.docker.internal:host-gateway"
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"     
    volumes:
      - ..:/app
      - ../data:/app/data
    environment:
       - SCRAPY_SETTINGS_MODULE=crawlers.settings
    command: scrapy crawl batdongsan